# Tên ứng dụng
spring.application.name=ktx-food-delivery-system

# Cổng chạy server (mặc định Spring Boot là 8080)
server.port=8080

# Cho phép format JSON dễ đọc khi debug
spring.jackson.serialization.indent-output=true

# Hiển thị log chi tiết hơn khi phát triển
logging.level.com.ktxfood=DEBUG

# Cho phép CORS để frontend (chạy port khác, VD 5500 hoặc 5173) gọi được API
spring.mvc.cors.allowed-origins=*